**Classes**

In [1]:
# defining the class
class Point:
    # defining the default constructor
    def __init__(self):
        pass

In [2]:
# defining the class
class Point:
    # defining the constructor
    def __init__(self, name,x, y):
        self.name = name
        self.x = x
        self.y = y

In [4]:
# creating an object of the class
p1 = Point('P1', 2, 3)

In [9]:
print(p1.name + "(" + str(p1.x) + "," + str(p1.y) + ")")

P1(2,3)


In [18]:
# defining the class
class Point:
    # defining the constructor
    def __init__(self, name='P',x=0, y=0):
        self.name = name
        self.x = x
        self.y = y
    def display(self):
        # print(self.name + "(" + str(self.x) + "," + str(self.y) + ")")
        print('%s(%.2f,%.2f)' % (self.name, self.x, self.y))

In [19]:
p2=Point()

print(p2.name + "(" + str(p2.x) + "," + str(p2.y) + ")")

p2.display()

P(0,0)
P(0.00,0.00)


In [20]:
p3 = Point(x = 10, name = 'P3')

print(p3.name + "(" + str(p3.x) + "," + str(p3.y) + ")")

p3.display()

P3(10,0)
P3(10.00,0.00)


In [21]:
# defining the class
class Point:
    # defining the constructor
    def __init__(self, name,x, y):
        self.name = name
        self.x = x
        self.y = y
    def get(self):
        return '%s(%.2f,%.2f)' % (self.name, self.x, self.y)
    def display(self):
        print(self.get())

In [23]:
p4 = Point('P4', 4, 5)
p4.display()
p4.get()

P4(4.00,5.00)


'P4(4.00,5.00)'

**Python AI prerequisite**

Data Manipulation with Numpy

scalars

In [26]:
x=1
y=2

z=x+y
print(z)

3


Vectors

In [1]:
import numpy as np

x=np.array([1,2,3])
y=np.array([4,5,6])

print(x+y)

[5 7 9]


Mathematique Object

In [2]:
x= np.array([1,2,3])

In [3]:
x.dtype

dtype('int32')

In [7]:
x=np.array([1,2,300], dtype=np.uint8)

In [8]:
x # 300 is truncated to 44 because 300 is not representable in 8 bits 256+44=300 256 is the maximum value that can be represented in 8 bits

array([ 1,  2, 44], dtype=uint8)

In [9]:
x.ndim

1

In [10]:
x.shape

(3,)

In [11]:
type(x)

numpy.ndarray

In [12]:
x.sum()

47

In [13]:
x.max()

44

In [14]:
x.argmax() # index of the maximum value

2

In [15]:
x[0]

1

In [16]:
x[-1]

44

In [17]:
x[:2]

array([1, 2], dtype=uint8)

In [18]:
x[::-1]

array([44,  2,  1], dtype=uint8)

In [19]:
len(x)

3

In [20]:
x.tolist()

[1, 2, 44]

In [25]:
x

array([1, 2, 3])

In [23]:
L=[1,2,3]
x = np.array(L)

In [26]:
np.exp(x)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [ ]:
x/2